minimum_pre_commit_version: "3.2.0"
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        files: (^|/)(?:scripts/(?:test_.+|.+_test)|tests/.+)\.py$
        exclude: (^|/)_.*\.py$|(^|/)lit\.cfg\.py$
        args: ["--pytest-test-first"]
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/crate-ci/typos
    rev: v1.49.0
    hooks:
      - id: typos
        entry: typos
        args: []

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.9.1
    hooks:
      - id: pydoclint

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: conventional-commit-message
        name: conventional commit message
        entry: .githooks/commit-msg
        language: script
        stages: [commit-msg]
